### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by Vetm** [IUBH-Fallstudie/dash#3]
@sveah @dakuuu wollt ihr euch mal Gedanken über ein Logo machen?

**Comment by dakuuu** [comment]
Hab Grobe Ideen muss nur Zeit finden Sie umzusetzen...

[https://www.draw.io/#G15CPwjn1_K053kd6ajsKjhxnoj7QGwTht](url) 

Farben und alles stimmen nicht ✌️

**Comment by sveah** [comment]
Ich hab das heute erst gesehen. Die Mails von GitHub landen im "Unbekannt"-Ordner und da schaue ich nie rein... Wird das Logo noch woanders als oben im Browser und unter den Vorschlägen, wenn man einen neuen Tab öffnet, gezeigt? Dann würde ich eventuell nur irgendwas ganz einfaches wie dieses Dashboard-Logo von material.io machen, weil man eh fast nichts sieht.
