### ISSUE TITLE
Von Kurssuche zu Notenübersicht an der richtigen Stelle

### ISSUE THREAD

**Issue by sveah** [IUBH-Fallstudie/dash#6]

**Comment by Vetm** [comment]
Worum ging es hier nochmal genau?

**Comment by sveah** [comment]
Vielleicht das als kleinen Button noch anbringen, falls das möglich ist? Also wenn ich auf das Suche-Zeichen drücke, dann sehe ich ja alle Kurse und wenn ich jetzt da drauf drücke, kommt das Modulhandbuch (zumindest in 10% direkt :D ) und ein Button daneben, der dafür sorgt, dass sich die Suche wieder schließt und die Notenübersicht an der richtigen Stelle öffnet, wäre cool :)
