### ISSUE TITLE
[Fortschrittsbalken]: Kursanzahl ist falsch

### ISSUE THREAD

**Issue by Vetm** [IUBH-Fallstudie/dash#7]
Möglicher Fix wäre den Fortschritt auf Modulebene zu errechnen.

Ansonsten könnten wir mal in Erfahrung bringen, ob es wirklich keine Module mit mehr als zwei Kursen gibt.

**Comment by dakuuu** [comment]
Kurs mal Credits und das in Prozent wäre ne Idee oder???

**Comment by Vetm** [comment]
@dakuuu Credits für Kurse bzw. für's Studium gesamt bekommen wir nirgendwo zuverlässig her. Bis jetzt scheint mir die Modulebene immer noch am passendsten. @sveah noch Ideen dazu?
